version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitoring_net:
  ui:
    image: ${USER_NAME}/ui:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
    #  - ${EXT_PORT}:9292/tcp
      - 9292:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
      - monitoring_net
  post:
    image: ${USER_NAME}/post:logging
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - 5000:5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net
      - monitoring_net
  comment:
    image: ${USER_NAME}/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
      - monitoring_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
  monitoring_net:
