- name: Install docker on instance
  hosts: all
  become: true

  tasks:
  - name: Installing packages required for repo
    apt:
      update_cache: yes
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: Adding Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Adding docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: Installing Docker CE
    apt:
      update_cache: yes
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Removing docker-compose old file if it exists
    file:
      path: /usr/local/bin/docker-compose
      state: absent

  - name: Installing docker-compose
    uri:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: +x
