version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    volumes:
      - ./ui/:/app/:rw
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${EXT_PORT}:9292/tcp
    networks:
      - front_net
    command: /bin/sh -c "puma --debug -w 2"
    stdin_open: true
    tty: true
  post:
    build: ./post-py
    volumes:
      - ./post-py/:/app/:rw
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    volumes:
      - ./comment/:/app/:rw
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    command: /bin/sh -c "puma --debug -w 2"

volumes:
  post_db:

networks:
  back_net:
  front_net:
