- name: Deploying and launching GitLab in Docker container
  hosts: all
  become: true

  tasks:
  - name: Create GitLab directories
    file:
      path:
      - /srv/gitlab/config
      - /srv/gitlab/logs
      - /srv/gitlab/data
      state: directory
    
  - name: Launch Docker container
    docker_container:
      name: gitlab_container
      state: started
      image: gitlab/gitlab-ce:latest
      hostname: gitlab.example.com
      restart: yes
      env:
        GITLAB_OMNIBUS_CONFIG: "external_url '{{ ansible_host }}'"
      ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
